// react/comps/Cropper/_cropper.js
import React, { useEffect, useState, useRef } from "react";
import "cropperjs/dist/cropper.css";
import Cropper from "cropperjs";
import styled from "styled-components";
/**
 * @param {File} file
 * @param {Object} cropper - cropperjs options
 * @param {Function} onSubmit(base64) - 回调函数, 参数中包含裁切图片的base64
 * @param {Number} width - 需要的图片宽度, 高度根据比例自动计算
 */
export default function Crop({ file, cropper, onSubmit, width = 160 }) {
  const [show, setShow] = useState(false);
  const [src, setsrc] = useState("");
  const img = useRef(null);
  const preview = useRef(null);
  const crop = useRef(null);

  useEffect(() => {
    if (file) {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = e => {
        setShow(true);
        setsrc(e.target.result);
      };
    }
  }, [file]);

  const onImageLoad = e => {
    crop.current = new Cropper(img.current, {
      aspectRatio: 16 / 9,
      viewMode: 1,
      preview: preview.current,
      ...cropper
    });
  };

  const close = () => {
    setShow(false);
    crop.current.destroy();
  };

  const submit = () => {
    const canvas = crop.current.getCroppedCanvas({ width, minWidth: width });
    const dataURL = canvas.toDataURL("image/jpeg");
    onSubmit(dataURL);
    close();
  };

  const display = { display: show ? "block" : "none" };

  if (!file) return null;

  return (
    <Background style={display}>
      <Box>
        <Left>
          <Title>图片裁切</Title>
          <Workspace>
            <Img src={src} onLoad={onImageLoad} ref={img} />
          </Workspace>
        </Left>
        <Right>
          <RightTitle>效果预览</RightTitle>
          <Preview ref={preview} />
          <Actions>
            <Button onClick={close}>取消</Button>
            <ButtonOK onClick={submit}>确定</ButtonOK>
          </Actions>
        </Right>
      </Box>
    </Background>
  );
}

// Style
const Background = styled.div`
  background: rgba(0, 0, 0, 0.75);
  width: 100%;
  height: 100%;
  position: fixed;
  top: 0;
  left: 0;
  z-index: 20000;
`;

const Box = styled.div`
  width: 1000px;
  height: 600px;
  background: white;
  margin: auto;
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  overflow: hidden;
  display: flex;
`;

const Left = styled.div`
  flex-grow: 1;
  flex-direction: column;
  height: 100%;
  display: flex;
`;

const Title = styled.div`
  padding: 15px;
`;

const RightTitle = styled(Title)`
  padding-left: 0;
`;

const Workspace = styled.div`
  flex-grow: 1;
`;

const Right = styled.div`
  width: 300px;
  padding: 0 20px;
  display: flex;
  flex-direction: column;
  margin-left: 20px;
  flex-shrink: 0;
  height: 100%;
  flex-grow: 1;
  border-left: 1px solid rgb(235, 235, 235);
  background: rgb(245, 245, 245);
`;

const Preview = styled.div`
  width: 257px;
  height: 257px;
  overflow: hidden;
`;

const Img = styled.img`
  max-width: 100%;
`;
const Actions = styled.div`
  margin-top: 20px;
`;

const Button = styled.div`
  padding: 10px 0;
  text-align: center;
  font-size: 15px;
  background: rgb(255, 59, 0);
  color: white;
  margin: 10px 0;
  cursor: pointer;
  user-select: none;
`;

const ButtonOK = styled(Button)`
  background: rgb(13, 91, 232);
`;

// vue/cropper.vue
<!-- 图片裁剪  -->
<template>
  <div class="crop-bg" v-show="show" style="z-index: 20000">
    <div class="crop-box" :style="boxStyle">
      <div class="crop-title">图片裁剪</div>
      <div class="close" @click="close">X</div>
      <div class="crop-choose">
        <label for="crop-input">
          <input accept=".jpg, .jpeg, .png, .gif" id="crop-input" ref="input" type="file" @change="change" capture />
          <span class="crop-btn">选择图片</span>
        </label>
        <div v-show="ready" class="crop-btn crop-btn-crop" @click="crop">确定</div>
      </div>
      <div class="crop-content" :style="contentStyle">
        <img :src="src" @load="start" ref="img" class="thumb" />
      </div>
    </div>
  </div>
</template>
<script>
/**
 * 图片裁剪
 * @param {Boolean} visible 是否显示
 * @param {Array} layout [width,height] 裁剪框大小
 * @param {Array} size [width,height] 裁剪后图片大小
 * @param {Function} crop(base64) 裁剪后回调
 *
 * @description
 *<crop :visible.sync="shwoCrop" @crop="onCrop" :layout="[700,500]" :size="[160,160]" />
 */
import Cropper from "cropperjs";
import "cropperjs/dist/cropper.css";
export default {
  props: {
    visible: {
      type: Boolean,
      default: false,
    },
    layout: {
      type: Array,
      default: () => [800, 600], //[width,height]
    },
    size: {
      type: Array,
      default: () => [200, 200],
    },
  },
  data() {
    return {
      show: false,
      src: "",
      file: null,
      cropper: null,
      ready: false,
    };
  },

  watch: {
    visible(val) {
      this.show = val;
    },
  },
  computed: {
    ratio() {
      return this.size[0] / this.size[1];
    },
    boxStyle() {
      return {
        width: this.layout[0] + "px",
        height: this.layout[1] + "px",
      };
    },
    contentStyle() {
      return {
        height: this.layout[1] - 40 + "px",
      };
    },
    previewStyle() {
      const width = this.layout[0] * 0.3 * 0.8;
      return {
        width: width + "px",
        height: width * this.ratio + "px",
      };
    },
  },
  methods: {
    prevent(e) {
      e.stopPropagation();
    },
    start() {
      const self = this;
      this.stop();
      this.cropper = new Cropper(this.$refs.img, {
        aspectRatio: this.ratio,
        minCropBoxWidth: this.size[0],
        minCropBoxHeight: this.size[1],
        ready: () => (self.ready = true),
      });
    },
    read(files) {
      return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
          return resolve();
        }
        const file = files[0];
        if (/^image\/\w+$/.test(file.type)) {
          const reader = new FileReader();
          reader.onload = () => {
            this.src = reader.result;
            this.file = file;
            resolve();
          };
          reader.onerror = reject;
          reader.onabort = reject;
          reader.readAsDataURL(file);
        } else {
          reject("Please choose an image file.");
        }
      });
    },
    //裁切图片
    crop() {
      const canvas = this.cropper.getCroppedCanvas({
        width: this.size[0], //需要的尺寸
        height: this.size[1],
      });
      const base64 = canvas.toDataURL();
      this.$emit("crop", base64);
      this.close();
    },
    change({ target }) {
      this.read(target.files)
        .then(() => (target.value = ""))
        .catch((e) => {
          target.value = "";
          this.alert(e);
        });
    },
    alert(e) {
      window.alert(e && e.message ? e.message : e);
    },
    close() {
      this.src = "";
      this.stop();
      this.$emit("update:visible", false);
    },
    stop() {
      if (this.cropper) {
        this.cropper.destroy();
        this.cropper = null;
        this.ready = false;
      }
    },
  },
};
</script>
<style scoped>
.crop-bg {
  position: fixed;
  width: 100%;
  height: 100%;
  left: 0;
  top: 0;
  background: rgba(0, 0, 0, 0.281);
  user-select: none;
  z-index: 2000;
}
.crop-box {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
  background: rgb(255, 255, 255);
  width: 600px;
  height: 400px;
}
.crop-title {
  height: 50px;
  line-height: 50px;
  text-indent: 20px;
  background: rgb(245, 245, 245);
  position: relative;
  border-bottom: 1px solid #d4d4d4;
}
.crop-content {
  overflow: hidden;
  background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAAA3NCSVQICAjb4U/gAAAABlBMVEXMzMz////TjRV2AAAACXBIWXMAAArrAAAK6wGCiw1aAAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAABFJREFUCJlj+M/AgBVhF/0PAH6/D/HkDxOGAAAAAElFTkSuQmCC");
}

.crop-choose {
  overflow: hidden;
  position: absolute;
  top: 9px;
  left: 100px;
}
#crop-input {
  width: 1px;
  position: relative;
  left: -1px;
  opacity: 0.01;
}

.crop-btn {
  font-size: 13px;
  padding: 6px 15px;
  background: rgb(0, 60, 255);
  border-radius: 2px;
  color: white;
  display: inline-block;
  cursor: pointer;
  border-radius: 2px;
}
.crop-btn-crop {
  background: red;
  margin-left: 10px;
}
.thumb {
  max-width: 100%;
  max-height: 100%;
}
.close {
  display: inline-block;
  position: absolute;
  right: 10px;
  top: 10px;
  cursor: pointer;
}
</style>
